version: '3.4'

networks:
    platformserviceapi:

services:
    platformdb:
        container_name: app-db
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - 8082:1433
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Piyush@1529#
        networks:
            - platformserviceapi
    platformservice:
        container_name: platformserviceapi
        image: ${DOCKER_REGISTRY-}platformservice
        build:
            context: .
            dockerfile: PlatformService/Dockerfile
        ports:
            - 8080:80
        depends_on:
            - platformdb
        environment:
            - DB_HOST=platformservicedb
            - DB_NAME=platformapidb
            - DB_SA_PASSWORD=Piyush@1529#
        networks:
            - platformserviceapi
