apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-depl
spec: #for pods
  replicas: 1 #Kubernetes will ensure that 1 container replica is running
  selector: # this seleects the template with matching app name
    matchLabels:
      app: platformservice
  template: # defining info about pods
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
        - name: platformservice
          image: kumarpiyush21/platformservice:latest
---
# Cluster IP service config
apiVersion: v1
kind: Service
metadata: 
  name: platforms-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: platformservice
  ports:
    - name: platformservice
      protocol: TCP
      port: 80
      targetPort: 80
    - name: platformgrpc
      protocol: TCP
      port: 616
      targetPort: 616